Chore: document conventional commits
cloud-gov/pages-core pull request #4188
Opened 2023-07-12 21:21 UTC by drewbo

## Changes proposed in this pull request:
- Adds documentation around our use of [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) close https://github.com/cloud-gov/product/issues/2230

## security considerations
None

2023-07-12 21:29 UTC, drewbo commented
Note that the only "truly new" portion of this PR is the [bottom section of the new DEVELOPMENT.md document](https://github.com/cloud-gov/pages-core/pull/4188/files#diff-fc2a310fcfedfefb0046def697f932def80cbb1e78c689bc0af3c8eab3e33eceR452)

2023-07-13 19:00 UTC, apburnes submitted a review, later dismissed
📝

2023-07-13 19:50 UTC, svenaas commented on DEVELOPMENT.md
> +All commit messages on the default branch should follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification. In addition, an associated ticket number should be ad
It's not that unusual for one of our commits to need to reference a ticket on one of our other GitHub repos. Should this perhaps clarify what those should look like?

2023-07-13 19:51 UTC, svenaas commented on DEVELOPMENT.md
> +All commit messages on the default branch should follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification. In addition, an associated ticket number should be ad
For example, the runbook I just did was a ticket on this repo, but the implementation was a commit to a different repo.

2023-07-13 19:55 UTC, svenaas requested changes
One copyedit and a few suggestions.

2023-07-13 19:55 UTC, svenaas commented on DEVELOPMENT.md
> +- while the code is on a non-default branch, you can perform an [interative rebase](https://git-scm.com/docs/git-rebase) to rewrite the history.
```suggestion
- while the code is on a non-default branch, you can perform an [interactive rebase](https://git-scm.com/docs/git-rebase) to rewrite the history.
```

2023-07-13 19:55 UTC, svenaas commented on DEVELOPMENT.md
> +- prior to merging a PR, you can select either "Squash and merge" or "Rebase and merge" which will change the commit message(s) in the PR.
It **is** confusing that both of these are characterized as merges whereas merge commits on the feature branch are not allowed. This isn't particularly friendly, but I'm not sure how to make it better.

2023-07-17 22:22 UTC, apburnes approved these changes

2023-07-18 13:39 UTC, svenaas approved these changes

2023-07-18 16:32 UTC, merged