feat: Allow users to create custom domains to prepare launch
cloud-gov/pages-core pull request #4244
Opened 2023-08-30 23:00 UTC by apburnes

close #4176 

## Changes proposed in this pull request:
- Adds API endpoints to create, update and delete pending domains
- Adds UI to custom domains to create, edit, and delete pending domains

## security considerations
None

2023-08-31 15:52 UTC, svenaas requested changes
Couple of typos in error messages.

2023-08-31 15:52 UTC, svenaas commented on api/controllers/domain.js
> +          Please contact to cloud.gov Pages support.
```suggestion
          Please contact cloud.gov Pages support.
```

2023-08-31 15:52 UTC, svenaas commented on api/controllers/domain.js
> +          Please contact to cloud.gov Pages support.
```suggestion
          Please contact cloud.gov Pages support.
```

2023-08-31 21:45 UTC, drewbo requested changes
Voice discussion of controller improvements for finding matching sbc/domain name. Otherwise good

2023-09-05 15:43 UTC, apburnes commented on api/controllers/domain.js
> +          Please contact to cloud.gov Pages support.
Updated

2023-09-05 19:05 UTC, drewbo approved these changes

2023-09-05 19:07 UTC, svenaas approved these changes
LGTM

2023-09-05 19:44 UTC, merged