Add build task router and controller
cloud-gov/pages-core pull request #4247
Opened 2023-09-07 00:42 UTC by drewbo

## Changes proposed in this pull request:
- add build task router and controller
- close #4169

This includes some deviations from the initial proposal:
- the read routes don't include `/site/:site_id/` because the build ID can be used to authorize the user to read without it.
- the update route can now update any field (not just status) but includes a token check so that random users can't use it

This PR doesn't handle the full title of #4169 but it hits the acceptance criteria, happy to add more if needed

## security considerations
None

2023-09-07 13:33 UTC, drewbo commented
Removing review for now, going to add some tests

2023-09-07 23:48 UTC, drewbo commented
Noting here so I don't forget: the initial proposal used `tasks` rather than the singular `task`. Other portions of the API generally use the singular except for build `logs` which are fairly similar to this. Open to changing to singular if needed

2023-09-11 14:57 UTC, apburnes requested changes
Just a couple of questions on the build task status update

2023-09-11 14:57 UTC, apburnes commented on api/controllers/build-task.js
> +    if (task.token !== token) {
Should we be expiring tokens? After status becomes `success`, `skipped`, or `error`, the update endpoint will throw a forbidden response.

2023-09-11 14:57 UTC, apburnes commented on api/controllers/build-task.js
> +    if (task.token !== token) {
Should we be expiring tokens? After status becomes `success`, `skipped`, or `error`, the update endpoint will throw a forbidden response.

2023-09-11 14:57 UTC, apburnes commented on public/swagger/index.yml
Should we add the `/tasks/:build_task_id/:token` `PUT` endpoint?

2023-09-11 15:43 UTC, apburnes approved these changes

2023-09-11 16:10 UTC, merged