chore: Test shared user org select #4667
cloud-gov/pages-core pull request #4684
Opened 2024-11-25 22:19 UTC by apburnes

Closes #4667 

## Changes proposed in this pull request:
- Remove's default props and adds defaults to function args
- Fixes `htmlFor` to use the `id` prop
- Adds tests for select

## security considerations
None

2024-11-25 22:33 UTC, cloud-gov-pages-operations commented
## :robot: This is an automated code coverage report
  Total coverage (lines): **14.83%**
  Coverage diff: **0.27%** :chart_with_upwards_trend:

2024-11-26 14:01 UTC, drewbo requested changes
Two small items but looks good

2024-11-26 14:01 UTC, drewbo commented on frontend/shared/UserOrgSelect.jsx
>    className,
I'd initialize `className` as `''` since it's printed

2024-11-26 14:01 UTC, drewbo commented on frontend/shared/UserOrgSelect.test.jsx
> +  orgData: [
Even though this one is pretty small, I'd put this in another file so we have some organization fixture data to work with

2024-11-26 16:29 UTC, drewbo approved these changes

2024-11-26 16:32 UTC, merged